apiVersion: v1
kind: Namespace
metadata:
  name: robolineai
  labels:
    name: robolineai
    app.kubernetes.io/name: robolineai
    app.kubernetes.io/version: "1.0.0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: robolineai-monitoring
  labels:
    name: robolineai-monitoring
    app.kubernetes.io/name: robolineai-monitoring